# Simulation parameters

fleet:
  total_vehicles: 500

workers:
  total_workers: 50

time:
  duration_days: 31
  start_datetime: "2025-01-06 06:00"   # Monday morning

relocation:
  policy: "baseline"               # baseline / reactive / proactive / nightly
  check_interval_minutes: 60

  penalty_unmet:          45.00    # avg revenue per trip + round up for loss of goodwill:
                                       # baseline:  € 42.31
                                       # reactive:  € 42.35
                                       # proactive: € 42.31
  cost_per_relocation:    20.5553  # avg relocation cost:
                                       # reactive:  5351 @ € 100,597.09 --> € 18.79968043
                                       # proactive: 1615 @ €  36,032.28 --> € 22.31100929
  
  # Proactive policy
  time_step_minutes:        60     # avg intercity relocation duration
  planning_period_minutes:  180    # 2 steps: still see relocation decision effects
  lookahead_period_minutes: 180
  solver_time_limit_sec:    30

  # Nightly rebalancing
  trigger_hour: 2

demand:
  base_rate_weekday: 258           # total trips per hour
  base_rate_weekend: 319
  seed: 123